LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := FontAclonicaSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontAmaranteSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontAntipastoProSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontBariolSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontCagliostroSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontCoconSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontComfortaaSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontComicSansSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontCoolstorySourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontEvolveSansSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontExotwoSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontFifa2018SourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontFucekSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontGoogleSansOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontGrandHotelSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontHarmonySansOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontLGSmartGothicSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontLemonMilkSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontLinotteSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontNokiaPureSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontNothiingDotOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontNunitoSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontOdudaSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontOnePlusSansOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontOneUISansOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontOneplusSlateSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontOppoSansOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontQuandoSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontRedressedSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontReemKufiSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontRosemarySourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontSamsungOneSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontSimpleDaySourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontSonySketchSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontStoropiaSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontSurferSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FontUbuntuSourceOverlay
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := overlay/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

